name: OSS Contribution Graph

on:
  schedule:
    - cron: '15 19 * * *'
  workflow_dispatch:
    inputs:
      targets:
        description: 'Target repositories and usernames (e.g. kyungjunleeme@apache/airflow)'
        required: true
        type: string
        default: 'kyungjunleeme@apache/airflow'
      exclude_review:
        description: 'Exclude review contributions'
        required: false
        type: boolean
        default: false

env:
  DEFAULT_TARGETS: 'kyungjunleeme@apache/airflow'
  EXCLUDE_REVIEW: 'false'

jobs:
  update-histogram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # allow full history for pull

      - name: Set timestamp
        id: vars
        run: echo "timestamp=$(date +%Y%m%d-%H%M%S)" >> "$GITHUB_OUTPUT"

      - name: Generate Contribution Graph
        uses: peterxcli/gh-contribution-graph-action@main
        with:
          targets: ${{ github.event.inputs.targets || env.DEFAULT_TARGETS }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_dir: 'images'
          output_filename: "oss-graph-${{ steps.vars.outputs.timestamp }}.svg"
          exclude_authored_from_reviewed: ${{ github.event.inputs.exclude_review || env.EXCLUDE_REVIEW }}

      - name: Commit and push updated image
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git pull origin $(git rev-parse --abbrev-ref HEAD)
          git add images/
          git commit -m "Update OSS contribution graph" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
